export const DICT = {
    signin: ['Sign In', 'Iniciar sesión'],
    classes: ['# Classes', '# Clases'],
    search: ['Search', 'Buscar'],
    groups: ['# Rooms', '# Habitaciones'],
    guidance: ['# Counselor', '# Consejero'],
    directMsg: ['# Direct Messages', '# Mensajes directos'],
    announcements: ['Announcements', 'Anuncios'],
    assignments: ['Assignments', 'Asignaciones'],
    teachers: ['Teachers', 'Maestre'],
    teacher: ['Teacher', 'Maestre'],
    teachingAssistants: ['Teaching Assistants', 'Enseñando Asistentes'],
    students: ['Students', 'Estudiantes'],
    guardians: ['Guardians', 'Guardianes'],
    classDiscuss: ['Discussion Room', 'Sala de discusión'],
    message: ['Message', 'Mensaje'],
    public: ['Public', 'Público'],
    private: ['Private', 'Privado'],
    setReminder: ['Set Reminder', 'Establecer recordatorio'],
    discussion: ['Discussion Room', 'Sala de Discusión'],
}
